##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.11.2] date: [Fri Jul 09 12:08:03 EEST 2021] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = STM32H7_MyBoard


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -O3


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

# LVGL is pinned to the v8.4.0 release because its native 8-bit color format is
# RGB332, which maps byte-for-byte to this board's LTDC L8 framebuffer CLUT.
LVGL_VERSION = v8.4.0
LVGL_COMMIT = 4495f428630cc1741bd8bfd977f080e8460e8e8d
LVGL_DIR = Middlewares/Third_Party/lvgl
LVGL_STAMP = $(LVGL_DIR)/.stm32h7_lvgl_8_4_0

# Missing included makefiles are remade before the build and then GNU make
# restarts itself. This makes a plain `make` fetch the pinned LVGL source once,
# after which the recursive source list below is available on the restarted pass.
ifeq ($(filter clean distclean,$(MAKECMDGOALS)),)
-include $(LVGL_STAMP)
endif

ifneq ($(wildcard $(LVGL_DIR)/lvgl.h),)
LVGL_C_SOURCES := $(shell find $(LVGL_DIR)/src -type f -name '*.c' | sort)
else
LVGL_C_SOURCES :=
endif

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/main.c \
Core/Src/gpio.c \
Core/Src/ltdc.c \
Core/Src/rtc.c \
Core/Src/dma.c \
Core/Src/stm32h7xx_it.c \
Core/Src/stm32h7xx_hal_msp.c \
Core/Src/tda998x.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rtc.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rtc_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cortex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_ltdc.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_ltdc_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_gpio.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hsem.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_mdma.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2c.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2c_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_exti.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim_ex.c \
Core/Src/system_stm32h7xx.c \
Core/Src/fmc.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_fmc.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sdram.c \
Core/Src/dma2d.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma2d.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_usb.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hcd.c \
Core/Src/i2c.c \
Core/Src/i2s.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2s.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2s_ex.c \
USB_HOST/Target/usbh_conf.c \
USB_HOST/Target/usbh_platform.c \
USB_HOST/App/usb_host.c \
Middlewares/ST/STM32_USB_Host_Library/Core/Src/usbh_core.c \
Middlewares/ST/STM32_USB_Host_Library/Core/Src/usbh_ctlreq.c \
Middlewares/ST/STM32_USB_Host_Library/Core/Src/usbh_ioreq.c \
Middlewares/ST/STM32_USB_Host_Library/Core/Src/usbh_pipes.c \
Middlewares/ST/STM32_USB_Host_Library/Class/HID/Src/usbh_hid.c \
Middlewares/ST/STM32_USB_Host_Library/Class/HID/Src/usbh_hid_keybd.c \
Middlewares/ST/STM32_USB_Host_Library/Class/HID/Src/usbh_hid_mouse.c \
Middlewares/ST/STM32_USB_Host_Library/Class/HID/Src/usbh_hid_parser.c \
Core/Src/adc.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_adc.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_adc_ex.c \
Core/Src/lv_port.c \
Core/Src/pixel_lab.c \
$(LVGL_C_SOURCES)

# ASM sources
ASM_SOURCES =  \
startup_stm32h743xx.s


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
OD = $(PREFIX)objdump
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m7

# fpu fpv5-sp-d16 (949,736 bytes) 55ms/73ms 40ms/53ms -Wdouble-promotion -fsingle-precision-constant
#        fpv5-d16 (947,192 bytes) 55ms/73ms 40ms/53ms
# LTDC_VID_FORMAT 10
FPU = -mfpu=fpv5-d16

FPU_FLAGS = -Wdouble-promotion -fsingle-precision-constant

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI) -DARM_MATH_CM7 -D__FPU_PRESENT

# INCLUDES_LIBS_H7=Drivers/CMSIS/Lib/GCC/libarm_cortexM7lfsp_math.a
INCLUDES_LIBS_H7=Drivers/CMSIS/Lib/GCC/libarm_cortexM7lfdp_math.a

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32H743xx \
-DLV_CONF_INCLUDE_SIMPLE


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IDrivers/STM32H7xx_HAL_Driver/Inc \
-IDrivers/STM32H7xx_HAL_Driver/Inc/Legacy \
-IDrivers/CMSIS/Device/ST/STM32H7xx/Include \
-IDrivers/CMSIS/Include \
-IDrivers/CMSIS/DSP/Include \
-IUSB_HOST/App \
-IUSB_HOST/Target \
-IMiddlewares/ST/STM32_USB_Host_Library/Core/Inc \
-IMiddlewares/ST/STM32_USB_Host_Library/Class/HID/Inc \
-I$(LVGL_DIR) \
-I$(LVGL_DIR)/src \
-I$(LVGL_DIR)/demos

# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections $(FPU_FLAGS)
CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -std=gnu11 -Wall -fdata-sections -ffunction-sections $(FPU_FLAGS)

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32H743IITx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections $(INCLUDES_LIBS_H7)

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects. Preserve each source path below build/ so LVGL files with
# identical basenames in different subdirectories can never collide.
OBJECTS = $(patsubst %.c,$(BUILD_DIR)/%.o,$(C_SOURCES))
OBJECTS += $(patsubst %.s,$(BUILD_DIR)/%.o,$(ASM_SOURCES))

$(BUILD_DIR)/%.o: %.c Makefile
	@mkdir -p $(dir $@)
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(patsubst %.o,%.lst,$@) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile
	@mkdir -p $(dir $@)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir -p $@

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)

flash: $(BUILD_DIR)/$(TARGET).bin
	STM32_Programmer_CLI -c port=SWD -w $< 0x08000000 -rst

disasm:
	$(OD) -j .rodata -j .text -d -Mforce-thumb $(BUILD_DIR)/$(TARGET).elf > $(TARGET).asm

#######################################
# LVGL dependency
#######################################
$(LVGL_STAMP):
	@mkdir -p $(dir $(LVGL_DIR))
	@if [ ! -f "$(LVGL_DIR)/lvgl.h" ]; then \
		echo "Fetching LVGL $(LVGL_VERSION)..."; \
		rm -rf "$(LVGL_DIR)"; \
		git clone --quiet --depth 1 --branch "$(LVGL_VERSION)" https://github.com/lvgl/lvgl.git "$(LVGL_DIR)"; \
	fi
	@if [ -d "$(LVGL_DIR)/.git" ]; then \
		test "$$(git -C "$(LVGL_DIR)" rev-parse HEAD)" = "$(LVGL_COMMIT)" || \
		  (echo "Unexpected LVGL commit; expected $(LVGL_COMMIT)" >&2; exit 1); \
	fi
	@printf '# Auto-generated LVGL $(LVGL_VERSION) source stamp.\n' > "$@"

.PHONY: lvgl-fetch vendor-lvgl distclean
lvgl-fetch vendor-lvgl: $(LVGL_STAMP)

# clean keeps the downloaded third-party dependency; distclean removes it too.
distclean: clean
	-rm -rf $(LVGL_DIR)

#######################################
# dependencies
#######################################
-include $(OBJECTS:.o=.d)

# *** EOF ***
