#!/usr/bin/env python3
"""Generate C headers for TNC155B/Q, both using the FRANK PLC 23460102."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path

from build_frank_rom import build_frank_image


ROMSETS = {
    "tnc155b": (
        ("p1", "2340201A_nr1.rom", "CLP character-generator/font ROM"),
        ("p2", "2340202C_nr2.rom", "CLP TMS9995 program ROM"),
        ("p3", "2340083E_nr3_finnish.rom", "MAIN reset, services and Finnish dialog ROM"),
        ("p4", "2340204D_nr4.rom", "MAIN parser, tables and CLP payload ROM"),
        ("p5", "2340005E_nr5.bin", "MAIN NC and motion runtime ROM"),
        ("p6", "2346166A_nr6.rom", "TNC155B P6 support ROM + FRANK PLC 23460102"),
    ),
    "tnc155q": (
        ("p1", "Heidenhain-Nr1-2340003MNr.1.BIN", "CLP character-generator/font ROM"),
        ("p2", "Heidenhain-Nr2-2340003MNr.2.BIN", "CLP TMS9995 program ROM"),
        ("p3", "Heidenhain-Nr3-2340003MNr.3.BIN", "MAIN reset, services and dialog ROM"),
        ("p4", "Heidenhain-Nr4-2340003MNr.4.BIN", "MAIN parser and NC program ROM"),
        ("p5", "Heidenhain-Nr5-2340003MNr.5.BIN", "MAIN NC/support ROM"),
        ("p6", "Heidenhain-Nr6-WF5-23496BFDIPLC.BIN", "TNC155Q P6 support ROM + FRANK PLC 23460102"),
    ),
}


def emit_array(out: list[str], symbol: str, data: bytes) -> None:
    out.append(f"_Alignas(4) static const uint8_t {symbol}[{len(data)}] = {{")
    for offset in range(0, len(data), 16):
        row = ", ".join(f"0x{byte:02x}" for byte in data[offset : offset + 16])
        out.append(f"    {row},")
    out.append("};")
    out.append("")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("rom_dir", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--p5", type=Path,
                        help="verified P5 image overriding the B ROM-set copy")
    parser.add_argument("--only-set", choices=tuple(ROMSETS),
                        help="emit only one ROM set (used by STM32 firmware builds)")
    args = parser.parse_args()

    plc_source = args.rom_dir / "tnc155_standard_plc_23460102.txt"
    output = [
        "/* Generated by tools/embed_roms.py. Do not edit manually. */",
        "#ifndef TNC155_ROM_IMAGES_H",
        "#define TNC155_ROM_IMAGES_H",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "typedef struct tnc155_embedded_rom {",
        "    const char *socket;",
        "    const char *filename;",
        "    const char *role;",
        "    const uint8_t *data;",
        "    size_t size;",
        "    const char *sha256;",
        "} tnc155_embedded_rom;",
        "",
    ]

    selected = ((args.only_set, ROMSETS[args.only_set]),) if args.only_set else ROMSETS.items()

    for set_name, roms in selected:
        records: list[tuple[str, str, str, int, str, str]] = []
        for short_name, filename, role in roms:
            path = (args.p5 if set_name == "tnc155b" and short_name == "p5" and args.p5
                    else args.rom_dir / filename)
            data = path.read_bytes()
            if short_name == "p6":
                data = build_frank_image(plc_source, data)
            symbol = f"{set_name}_rom_{short_name}"
            digest = hashlib.sha256(data).hexdigest()
            emit_array(output, symbol, data)
            records.append((short_name.upper(), filename, role, len(data), digest, symbol))

        output.append(
            f"static const tnc155_embedded_rom {set_name}_roms[{len(records)}] = {{"
        )
        for socket, filename, role, size, digest, symbol in records:
            output.append(
                f'    {{"{socket}", "{filename}", "{role}", {symbol}, {size}u, "{digest}"}},'
            )
        output.extend(
            (
                "};",
                f"static const size_t {set_name}_rom_count = {len(records)}u;",
                "",
            )
        )

    output.extend(("#endif", ""))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(output), encoding="ascii")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
